version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:    
    - POSTGRES_DB=location_development
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  web:
    build:    
      context: .
      dockerfile: Dockerfile    

    ports:
      - "3000:3000"

    depends_on:
      - db